### ISSUE TITLE
Documentation To-Do

### ISSUE THREAD

**Issue by jckwik** [McQuaidRobotics/frcscouting#1]
- Header data
  - Variables
  - Inputs
    - type
    - listdata
    - label
    - style
    - do
    - saveas
  - Output

**Comment by jckwik** [comment]
Still to-do:
  - [ ] Architecture discussion (question vs report)
  - [ ] Extent of what you can use in "do" commands
  - [ ] Discussion of question flow during matches and match-to-match
